version: "3.8"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
