version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "for i in 1 2 3 4 5; do migrate -path /migrations -database 'postgres://user:pass@db:5432/banking?sslmode=disable' up && exit 0 || sleep 3; done; exit 1"
    ]
    restart: "no"

  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: pass
      DB_NAME: banking
      JWT_SECRET: supersecretkey
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: noreply@example.com
      SMTP_PASS: strong_password
    depends_on:
      - db
      - mailhog
      - migrate

volumes:
  db-data:
